package com.china;

import org.mybatis.spring.annotation.MapperScan;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;


// Generated by https://start.springboot.io
// 优质的 spring/boot/data/security/cloud 框架中文文档尽在 => https://springdoc.cn
@MapperScan("com.china.mapper")
@SpringBootApplication
public class ChinaApplication {

    public static void main(String[] args) {
        SpringApplication.run(ChinaApplication.class, args);
        System.out.println("启动成功");
    }

}
